### ISSUE TITLE
erorrorrr

### ISSUE THREAD

**Issue by aamirxs** [devgaganin/Auto-Forward-Bot-V2#3]
10:48:53 AM - 32 - root - bot - INFO - aamir with for pyrogram v2.3.48 (Layer 189) started on @aamirxxbot.
10:48:53 AM - 38 - root - bot - INFO - **๏[-ิ_•ิ]๏ bot restarted !**
Traceback (most recent call last):
  File "/home/admin/Auto-Forward-Bot-V2/main.py", line 4, in <module>
    app.run()
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pyrogram/methods/utilities/run.py", line 81, in run
    run(self.start())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/bot.py", line 41, in start
    async for user in users:
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/motor/core.py", line 1425, in next
    if self.alive and (self._buffer_size() or await self._get_more()):
                                              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/synchronous/cursor.py", line 1205, in _refresh
    self._send_message(q)
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/synchronous/cursor.py", line 1100, in _send_message
    response = client._run_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/_csot.py", line 120, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 1754, in _run_operation
    return self._retryable_read(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 1863, in _retryable_read
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/_csot.py", line 120, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 1830, in _retry_internal
    ).run()
      ^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 2554, in run
    return self._read() if self._is_read else self._write()
           ^^^^^^^^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 2689, in _read
    self._server = self._get_server()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 2645, in _get_server
    return self._client._select_server(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 1649, in _select_server
    server = topology.select_server(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/synchronous/topology.py", line 398, in select_server
    server = self._select_server(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/synchronous/topology.py", line 376, in _select_server
    servers = self.select_servers(
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/synchronous/topology.py", line 283, in select_servers
    server_descriptions = self._select_servers_loop(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Auto-Forward-Bot-V2/myenv/lib/python3.11/site-packages/pymongo/synchronous/topology.py", line 333, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: ac-1evnexa-shard-00-02.rbt2mlh.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:992) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-1evnexa-shard-00-00.rbt2mlh.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:992) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-1evnexa-shard-00-01.rbt2mlh.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:992) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 670cf70d7e2d03877036e174, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-1evnexa-shard-00-00.rbt2mlh.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-1evnexa-shard-00-00.rbt2mlh.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:992) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-1evnexa-shard-00-01.rbt2mlh.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-1evnexa-shard-00-01.rbt2mlh.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:992) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-1evnexa-shard-00-02.rbt2mlh.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-1evnexa-shard-00-02.rbt2mlh.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:992) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
(myenv) root@ip-172-31-5-177:/home/admin/Aut

**Comment by devgaganin** [comment]
pymongo error re check credential
